/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC_BASE_ADDR    0x40012000UL
#define ADC_OFFSET_ADDR  0x40UL
#define ADC_ADDRESS      (ADC_BASE_ADDR + ADC_OFFSET_ADDR)
#define RCC_APB2_ENR     0x40023800UL
#define RCC_OFFSET       0x44UL
#define RCC_ADDRESS      (RCC_APB2_ENR + RCC_OFFSET)

int main(void)
{
	uint32_t *adccr1add = (uint32_t*) ADC_ADDRESS;
	uint32_t *rccaddenr = (uint32_t*) RCC_ADDRESS;
	*rccaddenr |= (1<<8);
	*adccr1add |= (1<<8);


    /* Loop forever */
	for(;;);
}
